name: Randoeffecto
version: ${project.version}
main: me.scorchingflame.randoeffecto.Randoeffecto
api-version: 1.19
authors: [ScorchingFlame]
description: idk bruv
commands:
   reloadPlayerData:
      description: Reloads Player Data
      usage: /<command>
      permission: randoeffecto.reloadPlayerData

   addMeSilk:
      description: Adds you to the silk touch list
      usage: /<command>
      permission: randoeffecto.test

   removeMeSilk:
         description: removes you to the silk touch list
         usage: /<command>
         permission: randoeffecto.test

   addMeSoul:
         description: Adds you to the soul list
         usage: /<command>
         permission: randoeffecto.test

   removeMeSoul:
         description: removes you to the soul list
         usage: /<command>
         permission: randoeffecto.test

   addEffect:
      description: Adds you to custom effect.
      usage: /addEffect <custom-effect-id> <amplifier (1-3)>
      permission: randoeffecto.test

   removeEffect:
         description: Removes you from custom effect.
         usage: /removeEffect <custom-effect-id> <amplifier (1-3)>
         permission: randoeffecto.test


permissions:
    randoeffecto.reloadPlayerData:
        description: Allows you to reload player data
        default: op

    randoeffecto.test:
        description: just testing purposes
        default: op

    randoeffecto.blessings.silkTouch:
        description: Allows the user to being able to get the silk touch custom effect