name: Randoeffecto
version: ${project.version}
main: me.scorchingflame.randoeffecto.Randoeffecto
api-version: 1.19
authors: [ScorchingFlame]
description: idk bruv
permissions:
    randoeffecto.reloadPlayerData:
        description: Allows you to reload player data
        default: op

    randoeffecto.test:
        description: just testing purposes
        default: op

    randoeffecto.myeffects:
        description: Permission for the command myeffects.
        default: true

    randoeffecto.blessings.silkTouch:
        description: Allows the user to being able to get the silk touch custom effect

    randoeffecto.admin.addeffects:
        description: Allows the user to add effects .
        default: op

    randoeffecto.admin.removeeffects:
        description: Allows the user to remove effects.
        default: op

    randoeffecto.admin.vieweffects:
        description: Allows the user to check other player's effect
        default: op